apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy
  namespace: envoygateway
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://mirror.gcr.io/envoyproxy/gateway-helm
  ref:
    tag: v1.6.2