apiVersion: v1
kind: Secret
metadata:
    name: universal-auth-credentials
    namespace: default
type: Opaque
stringData:
    clientId: ENC[AES256_GCM,data:+LBgzkWmQ2wUVJkwYM4tStXt5hSHcgHmpAgj/Duwwk1CBnt1,iv:Z8ufpiqDGdQrk7OpRN8kSEwtWk28sYfLbbYHGktiaAs=,tag:UCrsTblKEJbsLdV4ozZYVA==,type:str]
    clientSecret: ENC[AES256_GCM,data:TOhI92qvZDv/grLzVY2Dur58hWcA9kcz7n+Nh8KjgSFVRHWhC47elQ3F7jkPfWQuc7hsTJRKT9F4cLRFigR8uw==,iv:HheVhjwJUk+bYPW9qr5WQwzjglK3pYZgcq3MqBbQORg=,tag:tqxT77hWjOr5qmf2cwXqWw==,type:str]
sops:
    age:
        - recipient: age1h52e98zda9tg6zduxaew24tf3w43ur80ash7xq2k7tkw47qwey6qzs37hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWTZVTkdFUzlLdFAyOC9O
            QjJsa2pHUXJ4L1lkcFI3NTh5a0lvenIvOXdJCm5TdDF6TktON004ZjcyamFrN3FQ
            WVptcnFBd1JJQmVXMU9HV2xlbWl3RHMKLS0tIExZaGxrNjhoQ2VoQWJWYlE2bUl1
            ZFlQM2c2Z01YM0o5cU1mNnZMWDBYRXMKKdX4mgbt+vnGr/1yQUcFSI8N6tAqwwka
            15L7j/e3MMnY2QF+oKGp83GFCUZCAEgkJL3sN1Q77PvI/mbmWaoaig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T13:42:56Z"
    mac: ENC[AES256_GCM,data:lsUA7CbhgDKbpsriwCpzYoAZgV36vqdRg0a9KtpYJvLRGLOE/LZvzgoJwZMJeDsKRMTyL22r8TA4dd4bqist7aP84F2yPUzlW4D5XvUQYI2LWEhyVHr46H5YilKHcUqsCHhRVDuTD5lMl3pUGplBT7K6ObMCR8jQo7nvWPQwzVc=,iv:MyNNGQbR9VBl48GWnTKJ0385moqyMOSl7mEXESFq43E=,tag:xF2e2grHvXWKz8tXyEHfFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
