apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    cnpg.io/reload: "true"
  labels:
    app.kubernetes.io/name: postgres
  name: postgres-user
  namespace: pocketid
spec:
  target:
    name: postgres-user
    template:
      data:
        password: '{{ .password }}'
        username: pocketid
      type: kubernetes.io/basic-auth
  secretStoreRef:
    kind: SecretStore
    name: secretstore
  data:
    - remoteRef:
        key: postgres-password
      secretKey: password
