apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clustersecret
  namespace: clustersecret
spec:
  interval: 30m
  chart:
    spec:
      chart: clustersecret
      version: 0.2.1
      sourceRef:
        kind: HelmRepository
        name: clustersecret
        namespace: clustersecret
  install:
    remediation:
      retries: 1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
