apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: bitwardensecret
spec:
  organizationId: "3a42acff-dfc7-4b1b-9d5e-afe8009837e6"
  secretName: tailscale_secret
  map:
    - bwSecretId: 75d6e603-b6ad-4df3-b737-b2d800b44713
      secretKeyName: tailscale_client_id
    - bwSecretId: a29219eb-0b34-461d-8135-b2d800b46816
      secretKeyName: tailscale_client_secret
  authToken:
    secretName: bw-auth-token
    secretKey: token
