apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 30m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.82.5
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
  install:
    remediation:
      retries: 1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: Secret
      name: tailscale-secrets
      valuesKey: clientId
      targetPath: oauth.clientId
    - kind: Secret
      name: tailscale-secrets
      valuesKey: clientSecret
      targetPath: oauth.clientSecret
