apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: tailscale
  namespace: tailscale
spec:
  statefulSet:
    pod:
      tailscaleContainer:
        resources:
          limits:
            squat.ai/tun: "1"
        securityContext:
          allowPrivilageEscalation: false
          capabilities:
            drop:
              - ALL
            add:
              - NET_ADMIN
