apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: tailscale
spec:
  provider:
    vault:
      server: "https://vault-0.vault-internal:8200"
      path: "secret"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
