apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
spec:
  interval: 30m
  chart:
    spec:
      chart: vault
      version: 0.30.0
      sourceRef:
        kind: HelmRepository
        name: vault
        namespace: vault
  install:
    remediation:
      retries: 1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    server:
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          external-dns.alpha.kubernetes.io/hostname: vault.kdmorris.dev
          kubernetes.io/tls-acme: "true"
        ingressClassName: nginx
        activeService: true
        hosts:
          - host: vault.kdmorris.dev
        tls:
        - secretName: vault.kdmorris.dev
          hosts:
          - vault.kdmorris.dev
      affinity: ""
      ha:
        enabled: true
        raft: 
          enabled: true
          setNodeId: true
          config: |
            cluster_name = "vault-integrated-storage"
            storage "raft" {
               path    = "/vault/data/"
            }

            listener "tcp" {
               address = "0.0.0.0:8200"
               cluster_address = "0.0.0.0:8201"
               tls_disable = 1
            }

            ui = true

            service_registration "kubernetes" {}

