apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy
  namespace: envoygateway
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: forgejo
  install:
    remediation:
      retries: 1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: ConfigMap
      name: forgejo-config
    - kind: Secret
      name: postgres-creds
      valuesKey: password
      targetPath: gitea.config.database.PASSWD
    - kind: Secret
      name: forgejo-oauth
      valuesKey: secret
      targetPath: gitea.oauth.secret
