apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: forgejo
  namespace: forgejo
spec:
  interval: 5m
  url: oci://code.forgejo.org/forgejo-helm/forgejo
  ref:
    tag: 15.0.3