apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-oauth
  namespace: forgejo
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: secretstore
    kind: SecretStore
  target:
    name: forgejo-oauth
  data:
    - secretKey: secret
      remoteRef:
        key: forgejoOauthSecret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-bootstrap-creds
  namespace: forgejo
spec:
  refreshInterval: 24h

  secretStoreRef:
    name: secretstore
    kind: SecretStore

  target:
    name: postgres-bootstrap-creds
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: forgejo
        password: "{{ .password }}"

  data:
    - secretKey: password
      remoteRef:
        key: FORGEJO_POSTGRES_PASSWORD
