apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: passwordgenerator
  namespace: forgejo
spec:
  length: 128
  digits: 10
  symbols: 10
  symbolCharacters: "-_$!"
  noUpper: false
  allowRepeat: true
