apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externalsecrets
  namespace: externaldns
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
   name: secrets
  data:
    - secretKey: apiToken
      remoteRef:
        key: cloudflare
        property: apiToken
