apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: secretstore
  namespace: headlamp
spec:
  provider:
    infisical:
      hostAPI: https://eu.infisical.com
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            name: infisical-auth
          clientSecret:
            key: clientSecret
            name: infisical-auth
      secretsScope:
        projectSlug: home-0l-uq
        environmentSlug: prod
