apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infisical
spec:
  interval: 30m
  chart:
    spec:
      chart: secrets-operator
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: infisical
  install:
    remediation:
      retries: 1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
