apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mayastor-1
  annotations:
    storageclass.kubernetes.io/is-default-class: true
parameters:
  protocol: nvmf
  repl: "1"
  fstype: "xfs"
provisioner: io.openebs.csi-mayastor
