---
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: tw1_pool
  namespace: openebs
spec:
  node: tw1
  disks: ["aio:///dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1"]
---
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: tw2_pool
  namespace: openebs
spec:
  node: tw2
  disks: ["aio:///dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1"]
---
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: tw3_pool
  namespace: openebs
spec:
  node: tw3
  disks: ["aio:///dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1"]
---
