apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: openebs
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: openebs
  install:
    remediation:
      retries: 1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    io_engine:
      coreList: '{1,2}'
    mayastor:
      csi:
        node:
          initContainers:
            enabled: false
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
    zfs-localpv:
      zfsNode:
        encrKeysDir: /var/openebs/keys
