apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-secrets
  namespace: tailscale
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: secretstore
    kind: SecretStore
  target:
   name: tailscale
  data:
    - secretKey: clientId
      remoteRef:
        key: tailscaleClientId
    - secretKey: clientSecret
      remoteRef:
        key: tailscaleClientSecret
