apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-password
  namespace: pocketid
spec:
  refreshInterval: 30m
  target:
    name: postgres-password
  dataFrom:
    - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: passwordgenerator
