apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: postgresPassword
  namespace: pocketid
spec:
  refreshInterval: 30d
  secretStoreRefs:
    - name: secretstore
      kind: secretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1beta1
      kind: Password
      name: passwordgenerator
  data:
   - match:
      secretKey: password
      remoteRef:
        remoteKey: pocketidPostgresPassword
