apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-password
  namespace: pocketid
spec:
  refreshInterval: 30d
  target:
    name: postgres-password
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: passwordgenerator
