apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: secretstore
  namespace: pocketid
spec:
  provider:
    infisical:
      hostAPI: https://eu.infisical.com
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            name: infisical-auth
          clientSecret:
            key: clientSecret
            name: infisical-auth
      secretsScope:
        projectSlug: home-0l-uq
        environmentSlug: prod
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: k8s-store
  namespace: pocketid
spec:
  provider:
    kubernetes:
      # with this, the store is able to pull only from `default` namespace
      remoteNamespace: pocketid
      server:
        url: "https://myapiserver.tld"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
