apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-cron-job
  namespace: renovate
spec:
  schedule: '@hourly'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: renovate/renovate:42.29
              env:
              - name: RENOVATE_CONFIG_FILE
                value: '/opt/renovate/config.json'
              - name: RENOVATE_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: github
                    key: RENOVATE_TOKEN
              - name: LOG_LEVEL
                value: "DEBUG"
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/renovate/
              securityContext:
                allowPrivilegeEscalation: false
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
                capabilities:
                  drop:
                    - ALL
          restartPolicy: Never
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
                items:
                  - key: "config.json"
                    path: "config.json"
