apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: continuwuity
  namespace: matrix
spec:
  chart:
    spec:
      chart: conduwuit
      sourceRef:
        kind: HelmRepository
        name: continuwuity
      version: 
  interval: 1m0s
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: continuwuity-config
