apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: continuwuity-data
  namespace: matrix
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  storageClassName: mayastor-2
