apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: renovate-secrets
  namespace: renovate
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: secretstore
    kind: SecretStore
  target:
    name: github
    template:
      type: Opaque
      stringData:
        RENOVATE_TOKEN: "{{ .RENOVATE_TOKEN }}"
        RENOVATE_GITHUB_COM_TOKEN: "{{ .RENOVATE_TOKEN }}"
        LOG_LEVEL: "DEBUG"
  stringData:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: renovateGitHubToken
        decodingStrategy: None
