apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-secrets
  namespace: renovate
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: secretstore
    kind: SecretStore
  target:
    name: github
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: renovateGitHubToken
