apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: renovate-secrets
  namespace: renovate
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: secretstore
    kind: SecretStore
  target:
   name: github
  data:
    - secretKey: accessToken
      remoteRef:
        key: renovateGitHubToken
        decodingStrategy: Base64URL
