apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: matrix
    component: whatsapp-bridge
  name: whatsapp-bridge-data
  namespace: matrix
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  storageClassName: mayastor-2
