apiVersion: v1
kind: Service
metadata:
  labels:
    app: matrix
    component: whatsapp-bridge
  name: whatsapp-bridge
  namespace: matrix
spec:
  internalTrafficPolicy: Cluster
  publishNotReadyAddresses: true
  ports:
  - port: 8082
    protocol: TCP
    targetPort: http
  selector:
    app: matrix
    component: whatsapp-bridge
  sessionAffinity: None
  type: ClusterIP
