apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: headlamp-vc
  namespace: headlamp
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: mayastor-3
