apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bitwarden
spec:
  interval: 30m
  chart:
    spec:
      chart: sm-operator
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bitwarden
        namespace: bitwarden
  install:
    remediation:
      retries: 1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    settings:
      bwSecretRefreshInterval: 180
