apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: forgejo
  labels:
    app.kubernetes.io/name: forgejo
spec:
  instances: 2

  storage:
    size: 7Gi
  
  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
      secret:
        name: postgres-creds

# TODO Setup and configure Backup for Postgres 
#  backup:

  resources:
    limits:
      cpu: 400m
      memory: 420Mi
    requests:
      cpu: 130m
      memory: 300Mi
