apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: forgejo
spec:
  instances: 2

  imageName: ghcr.io/cloudnative-pg/postgresql:18.3-system-trixie

  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
      secret:
        name: postgres-bootstrap-creds

  enableSuperuserAccess: false

  storage:
    size: 10Gi

  postgresql:
    parameters:
      wal_level: logical
