apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.2
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: nginx
  install:
    remediation:
      retries: 1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      podLabels:
        tailscale.com/proxy-class: "tun-access"
      admissionWebhooks:
        enabled: false
      config:
        ssl-redirect: "true"
        force-ssl-redirect: "true"
      replicaCount: 1
      service:
        labels:
          tailscale.com/proxy-class: "tun-access"
        type: LoadBalancer
        loadBalancerClass: tailscale
      ingressClassResource:
        default: false
      watchIngressWithoutClass: false
      metrics:
        enabled: false
        serviceMonitor:
          enabled: false
