apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: nginx
  namespace: nginx
spec:
  provider:
    vault:
      server: "http://vault-0.vault-internal.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
