apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-secrets
  namespace: cloudflared
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: secretstore
    kind: SecretStore
  target:
    template:
      data:
        values.yaml: |-
          cloudflare:
            accountId: "{{ .CLOUDFLARE_ACCOUNT_ID }}"
            apiToken: "{{ .CLOUDFLARE_API_TOKEN }}"
  data:
    - secretKey: CLOUDFLARE_ACCOUNT_ID
      remoteRef:
        key: cloudflareAccountId
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: cloudflareTunnelApiToken
