apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  chart:
    spec:
      chart: cloudflare-tunnel-ingress-controller
      sourceRef:
        kind: HelmRepository
        name: cloudflared
      version: 0.0.21
  interval: 1m0s
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: cloudflared-config
    - kind: Secret
      name: cloudflared-secrets
