cloudflare:
  tunnelName: "ltp-homelab"

ingressClass:
  name: cloudflare

replicaCount: 2

cloudflared:
  image:
    repository: cloudflare/cloudflared
    pullPolicy: IfNotPresent
    tag: 2026.3.0
  replicaCount: 1
  protocol: auto
  extraArgs: []

cloudflaredServiceMonitor:
  create: false
