apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externaldns
  namespace: externaldns
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: secretstore
    kind: SecretStore
  target:
    name: cloudflare
    template:
      type: Opaque
      data:
        apiToken: "{{ .apiToken }}"
        domainFilters: "{{- .domainFilters | toJson }}"
  data:
    - secretKey: apiToken
      remoteRef:
        key: cloudflareApiToken
    - secretKey: domainFilters
      remoteRef:
        key: cloudflareDomainFilters
