apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ntfy

resources:
  - namespace.yml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - ingress.yaml

configMapGenerator: # will parse config from raw config to configmap,it allows for dynamic reload of application if additional app is deployed ie https://github.com/stakater/Reloader
    - name: server-config
      files: 
        - server.yml
